name: jsonqml

channels:
  - conda-forge

dependencies:
  - cmake
  - doxygen =1.9.1  # [linux]
  - git
  - make  # [unix]
  - ninja
  - curl
  - mesa-libgl-devel-cos7-x86_64 # [unix]
  - qt=6.7.2
  - spdlog
